name: Github Context Flow

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    env:
      MY_ACTION: ${{github.action}}
    steps:
      - name: Running context
        run: echo "Hello ${MY_ACTION}"
    

