name: Custom Github Action

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Jay-Shah5109/githubaction-javascript@0.0.2
        with:
        # Greet Name
          who-to-greet: 'Jay Shah'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
