name: Test Workflow

on : ['push']

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print groupn messages
        run: |
          echo "::group::My Group Start Message"
          echo "Message 1"
          echo "MEssage 2"
          echo "::endgroup::My Group End Message"